
import { Plant } from '../types';

export const mockPlants: Plant[] = [
  {
    id: 1,
    name: 'Monstera Deliciosa',
    category: 'tropical',
    imageUrl: 'https://picsum.photos/seed/monstera/400/400',
    description: 'A popular houseplant with iconic split leaves. Thrives in bright, indirect light.',
    careLevel: 'easy',
    wateringFrequency: 'Weekly',
  },
  {
    id: 2,
    name: 'Fiddle Leaf Fig',
    category: 'tropical',
    imageUrl: 'https://picsum.photos/seed/fiddle/400/400',
    description: 'A stylish plant with large, violin-shaped leaves. Prefers consistent conditions.',
    careLevel: 'moderate',
    wateringFrequency: 'Every 7-10 days',
  },
  {
    id: 3,
    name: 'Boston Fern',
    category: 'fern',
    imageUrl: 'https://picsum.photos/seed/fern/400/400',
    description: 'A lush, feathery fern that loves high humidity and indirect light.',
    careLevel: 'moderate',
    wateringFrequency: 'Keep soil moist',
  },
  {
    id: 4,
    name: 'Snake Plant',
    category: 'succulent',
    imageUrl: 'https://picsum.photos/seed/snake/400/400',
    description: 'Extremely resilient and known for its air-purifying qualities. Tolerates low light.',
    careLevel: 'easy',
    wateringFrequency: 'Every 2-4 weeks',
  },
  {
    id: 5,
    name: 'Orchid',
    category: 'flowering',
    imageUrl: 'https://picsum.photos/seed/orchid/400/400',
    description: 'An elegant flowering plant that produces stunning, long-lasting blooms.',
    careLevel: 'difficult',
    wateringFrequency: 'Weekly',
  },
  {
    id: 6,
    name: 'Juniper Bonsai',
    category: 'bonsai',
    imageUrl: 'https://picsum.photos/seed/bonsai/400/400',
    description: 'A classic outdoor bonsai tree that requires careful pruning and wiring.',
    careLevel: 'difficult',
    wateringFrequency: 'When soil is dry',
  },
  {
    id: 7,
    name: 'ZZ Plant',
    category: 'tropical',
    imageUrl: 'https://picsum.photos/seed/zzplant/400/400',
    description: 'A drought-tolerant plant with glossy, dark green leaves. Perfect for beginners.',
    careLevel: 'easy',
    wateringFrequency: 'Every 3-4 weeks',
  },
  {
    id: 8,
    name: 'Peace Lily',
    category: 'flowering',
    imageUrl: 'https://picsum.photos/seed/peacelily/400/400',
    description: 'Known for its beautiful white spathes and ability to thrive in lower light.',
    careLevel: 'easy',
    wateringFrequency: 'Weekly',
  },
];
